on:
  push:
  workflow_dispatch:
    inputs: 
      testInput: 
        description: "Test input"
        required: true
        default: "default"

jobs:
  push-job:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - run: |
          echo "This is the push job"
  
  dispatch-job:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'workflow_dispatch' }}
    outputs:
      h3_resolution: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: |
          echo "This is the dispatch job"
          echo "${{ inputs.testInput }} direct"
          echo "$TEST_INPUT through env"
          if [ $TEST_INPUT = "default" ]; then echo '::set-output name=test::"3 4"'; else echo '::set-output name=test::"3 4 5"'; fi
        env: 
          TEST_INPUT: ${{ inputs.testInput }}
      
  dependent-job:
    runs-on: ubuntu-22.04
    needs: [dispatch-job]
    steps:
      - run: |
          echo "This is the dependent job"
          echo "The output resolution is ${{ needs.dispatch-job.outputs.h3_resolution }}"
